name: Build Docker Image

on:
  push:
    branches: [prod]
    paths:
      - "backend/**"
      - "docker-compose.yml"

jobs:
  build: 
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gdg-backend:${{ steps.meta.outputs.tag }} ./backend

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gdg-backend:${{ steps.meta.outputs.tag }}