name: Deploy Backend

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/GDGOC-DGI-Website

            IMAGE_TAG="${{ github.event.workflow_run.head_sha }}"
            if [ -z "$IMAGE_TAG" ]; then
              IMAGE_TAG="${{ github.event.inputs.image_tag }}"
            fi

            export IMAGE_TAG=$IMAGE_TAG

            docker compose pull
            docker compose up -d